// src/components/primitives/button-group/button-group.tsx
import * as React from 'react'
import type { ButtonProps } from '../button/button.tsx'

interface ButtonGroupProps extends React.PropsWithChildren {
  size?: ButtonProps['size']
  variant?: ButtonProps['variant']
}

function ButtonGroup({ children, size, variant }: ButtonGroupProps) {
  return (
    <div className="flex flex-row ![&>*]:rounded-none ![&>*:first-child]:rounded-l-xl ![&>*:last-child]:rounded-r-xl">
      {React.Children.map(children, (child) => {
        return React.cloneElement(
          child as React.DetailedReactHTMLElement<any, HTMLElement>,
          {
            size,
            variant,
            className: 'not-last:border-r-none',
          },
        )
      })}
    </div>
  )
}

ButtonGroup.displayName = 'ButtonGroup'

export { ButtonGroup }

// src/components/primitives/button-group/ButtonGroup.vue
<script setup lang="ts">
import type { ButtonProps } from '@/components/primitives/button/button-variant'

const { size } = defineProps<Pick<ButtonProps, 'size'>>()
</script>

<template>
  <div class="w-fit flex flex-row ![&>*]:rounded-none ![&>*:first-child]:rounded-l-md ![&>*:last-child]:rounded-r-md ![&>*:not(:last-child)]:border-r-none">
    <slot :size="size" />
  </div>
</template>
